export const TREKS = [
  {
    slug: "kalsubai",
    name: "Kalsubai Peak Trek",
    tagline: "Highest peak of Maharashtra (1,646 m)",
    location: "Bari • Ahmednagar",
    distanceFromPuneKm: 175,
    difficulty: "Moderate",
    duration: "1N/1D",
    heightM: 1646,
    altitudeFt: 5400,
    bestSeason: "Monsoon to Winter",
    pricePerPerson: 1499,
    includes: ["Food", "Instructor", "First Aid", "Travelling"],
    exclusions: ["Personal expenses", "Bottled water", "Anything not in inclusions"],
    pickupPoints: ["9:00 PM – BMCC College (FC Road)", "9:15 PM – New Bus Stand (Shivajinagar)", "9:45 PM – Nashik Phata"],
    joinOptions: [{ from: "Pune", price: 1499, duration: "1N/1D" }, { from: "Kasara", price: 1099, duration: "1N/1D" }, { from: "Bari (Base)", price: 999, duration: "Day Trek" }],
    images: [
      "https://images.unsplash.com/photo-1519681393784-d120267933ba?q=80&w=1600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1521292270410-a8c2c730ea12?q=80&w=1600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?q=80&w=1600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?q=80&w=1600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=1600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1469474968028-56623f02e42e?q=80&w=1600&auto=format&fit=crop"
    ],
    upcomingDates: ["22 Aug 2025", "23 Aug 2025", "29 Aug 2025", "30 Aug 2025", "06 Sep 2025", "07 Sep 2025"],
    description: "Kalsubai, often called the Everest of Maharashtra, is a dream trek for many. Starting from Bari village, the trail moves through farmlands, iron ladders, and breezy plateaus before opening to a sunrise panorama above the clouds.",
    longAbout: "Have you felt a pull toward the mountains—beyond photos and reels—seeking quiet, grit and freedom? Kalsubai delivers exactly that. This is a straightforward yet rewarding climb inside the Kalsubai–Harishchandragad Sanctuary.",
    itinerary: [
      { day: "Day 1", title: "Departure from City", steps: ["09:00 PM – Pickup: BMCC College, FC Road", "09:15 PM – Pickup: New Bus Stand, Shivajinagar", "09:45 PM – Pickup: Nashik Phata", "Overnight travel to Bari"], meals: "None" },
      { day: "Day 2", title: "Trek to Kalsubai Peak", steps: ["03:00 AM – Reach Bari, freshen up", "03:30 AM – Start trek", "07:00 AM – Summit & sunrise views", "08:30 AM – Breakfast at/near top", "10:00 AM – Start descent", "02:00 PM – Reach base for lunch", "04:00 PM – Leave for Pune", "11:00 PM – Reach Pune"], meals: "Breakfast & Lunch" }
    ],
    thingsToCarry: ["2–3 L water (mandatory)", "Poncho/rain jacket", "Cap & sunscreen", "Trekking shoes with good grip", "Snacks (dry fruits/energy bars)", "Id proof, personal meds"],
    faq: [{ q: "Is Kalsubai suitable for beginners?", a: "Yes, with basic fitness. Ladders help at steep points." }, { q: "Are washrooms available?", a: "Basic facilities at base village; none on trail." }],
    similar: ["Harishchandragad", "Ratangad", "Sandhan Valley"]
  },
  {
    slug: "rajmachi",
    name: "Rajmachi Fort Trek",
    tagline: "Twin forts • meadows • fireflies (seasonal)",
    location: "Lonavala, Pune",
    distanceFromPuneKm: 65,
    difficulty: "Easy",
    duration: "1N/1D",
    heightM: 826,
    altitudeFt: 2710,
    bestSeason: "Monsoon & Post-monsoon",
    pricePerPerson: 1299,
    includes: ["Instructor", "First Aid", "Travelling"],
    exclusions: ["Meals unless specified", "Personal expenses"],
    pickupPoints: ["FC Road", "Shivajinagar", "Nashik Phata"],
    joinOptions: [ { from: "Pune", price: 1299, duration: "1N/1D" }, { from: "Lonavala", price: 999, duration: "Day/Night" } ],
    images: [
      "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?q=80&w=1600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1477414348463-c0eb7f1359b6?q=80&w=1600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=1600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1469474968028-56623f02e42e?q=80&w=1600&auto=format&fit=crop"
    ],
    upcomingDates: ["24 Aug 2025", "31 Aug 2025", "07 Sep 2025"],
    description: "Gentle trail with fort ruins, monsoon greens, and seasonal fireflies.",
    longAbout: "Perfect for beginners and groups. The trail is gentle and scenic.",
    itinerary: [
      { day: "Day 1", title: "Travel & Trek", steps: ["Depart Pune (evening)", "Reach Udhewadi", "Night walk / fireflies (seasonal)", "Camp/Rest"], meals: "Dinner (optional add-on)" },
      { day: "Day 2", title: "Explore & Return", steps: ["Sunrise at fort", "Explore ramparts", "Descend & return"], meals: "Breakfast" }
    ],
    thingsToCarry: ["Water 2L", "Rainwear", "Shoes with grip", "Snacks", "Headlamp"],
    faq: [ { q: "Is camping included?", a: "Optional add-on depending on batch." } ],
    similar: ["Lohagad", "Visapur", "Korigad"]
  },
  {
    slug: "andharban",
    name: "Andharban Jungle Trek",
    tagline: "Descending rainforest trail with waterfalls",
    location: "Tamhini Ghat",
    distanceFromPuneKm: 70,
    difficulty: "Moderate",
    duration: "1D",
    heightM: 700,
    altitudeFt: 2300,
    bestSeason: "Monsoon",
    pricePerPerson: 1699,
    includes: ["Travelling", "Instructor", "First Aid"],
    exclusions: ["Meals", "Forest permits (as applicable)"],
    pickupPoints: ["FC Road", "Shivajinagar", "Nashik Phata"],
    joinOptions: [ { from: "Pune", price: 1699, duration: "1D" } ],
    images: [
      "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?q=80&w=1600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?q=80&w=1600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=1600&auto=format&fit=crop"
    ],
    upcomingDates: ["23 Aug 2025", "30 Aug 2025", "06 Sep 2025"],
    description: "A lush rainforest traverse in peak monsoon, mostly descending with mist and streams.",
    longAbout: "Expect ankle-deep streams and canopies. Waterproof your bag.",
    itinerary: [
      { day: "Day 1", title: "The Jungle Walk", steps: ["Early morning start from Pune", "Trail entry (permits if required)", "Long descending trail", "Exit & return"], meals: "On your own / group halt" }
    ],
    thingsToCarry: ["Poncho", "Waterproof bag cover", "Anti-leech socks (optional)", "Snacks"],
    faq: [ { q: "Is it kid-friendly?", a: "Suitable for 10+ with supervision and stamina." } ],
    similar: ["Aadrai", "Devkund", "Bhimashankar"]
  },
  {
    slug: "harishchandragad",
    name: "Harishchandragad Trek (Konkan Kada)",
    tagline: "Iconic cliff views • temples • caves",
    location: "Pachnai / Khireshwar • Ahmednagar",
    distanceFromPuneKm: 170,
    difficulty: "Moderate",
    duration: "1N/1D",
    heightM: 1424,
    altitudeFt: 4672,
    bestSeason: "Post-monsoon to Winter (fireflies pre-monsoon)",
    pricePerPerson: 1599,
    includes: ["Travelling", "Instructor", "First Aid"],
    exclusions: ["Meals unless mentioned", "Personal expenses"],
    pickupPoints: ["FC Road", "Shivajinagar", "Nashik Phata"],
    joinOptions: [ { from: "Pune", price: 1599, duration: "1N/1D" } ],
    images: [
      "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=1600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1477414348463-c0eb7f1359b6?q=80&w=1600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1469474968028-56623f02e42e?q=80&w=1600&auto=format&fit=crop"
    ],
    upcomingDates: ["24 Aug 2025", "31 Aug 2025", "07 Sep 2025"],
    description: "Famed for the horseshoe-shaped Konkan Kada and ancient Kedareshwar cave temple.",
    longAbout: "Trail options via Pachnai (easier) or Khireshwar (longer).",
    itinerary: [
      { day: "Day 1", title: "Travel & Base", steps: ["Evening departure", "Reach base village", "Briefing / rest"], meals: "Optional dinner" },
      { day: "Day 2", title: "Summit & Return", steps: ["Early start", "Temple & Konkan Kada", "Descend", "Back to Pune"], meals: "Breakfast" }
    ],
    thingsToCarry: ["Water 2L", "Warm layer (windy at top)", "Headlamp", "Snacks"],
    faq: [ { q: "Konkan Kada safe?", a: "Stay behind caution lines; windy edges." } ],
    similar: ["Ratangad", "Kalsubai", "Sandhan Valley"]
  },
  {
    slug: "ratangad",
    name: "Ratangad Fort Trek (Bhandardara)",
    tagline: "AMK views • natural ‘Nedhe’ window",
    location: "Bhandardara • Ahmednagar",
    distanceFromPuneKm: 180,
    difficulty: "Moderate",
    duration: "1N/1D",
    heightM: 1297,
    altitudeFt: 4255,
    bestSeason: "Post-monsoon & Winter",
    pricePerPerson: 1499,
    includes: ["Travelling", "Instructor", "First Aid"],
    exclusions: ["Meals"],
    pickupPoints: ["FC Road", "Shivajinagar"],
    joinOptions: [ { from: "Pune", price: 1499, duration: "1N/1D" } ],
    images: [
      "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?q=80&w=1600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?q=80&w=1600&auto=format&fit=crop"
    ],
    upcomingDates: ["31 Aug 2025", "07 Sep 2025", "14 Sep 2025"],
    description: "A panoramic fort with the iconic rock window and AMK views.",
    longAbout: "Good mix of ladders, forest paths, and ruins. Sunrises are special.",
    itinerary: [
      { day: "Day 1", title: "Travel & Stay", steps: ["Evening bus", "Base stay / homestay"], meals: "Own / add-on" },
      { day: "Day 2", title: "Climb & Explore", steps: ["Early start", "Nedhe viewpoint", "Explore fort", "Descend & return"], meals: "Breakfast" }
    ],
    thingsToCarry: ["Water 2L", "Shoes with grip", "Sun cap", "Snacks"],
    faq: [ { q: "Is camping allowed?", a: "Subject to local rules; we plan safe batches." } ],
    similar: ["Harishchandragad", "AMK", "Kalsubai"]
  },
  {
    slug: "harihar",
    name: "Harihar Fort Trek",
    tagline: "Famous near-vertical rock-cut steps",
    location: "Trimbak • Nashik",
    distanceFromPuneKm: 245,
    difficulty: "Hard",
    duration: "1N/1D",
    heightM: 1120,
    altitudeFt: 3675,
    bestSeason: "Post-monsoon & Winter",
    pricePerPerson: 1699,
    includes: ["Travelling", "Instructor", "First Aid"],
    exclusions: ["Meals"],
    pickupPoints: ["FC Road", "Shivajinagar"],
    joinOptions: [ { from: "Pune", price: 1699, duration: "1N/1D" } ],
    images: [
      "https://images.unsplash.com/photo-1469474968028-56623f02e42e?q=80&w=1600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=1600&auto=format&fit=crop"
    ],
    upcomingDates: ["07 Sep 2025", "14 Sep 2025", "21 Sep 2025"],
    description: "The steep staircase is thrilling; avoid during heavy downpours.",
    longAbout: "Short yet intense climb with spectacular rampart views.",
    itinerary: [ { day: "Day 1", title: "Travel & Trek", steps: ["Night travel", "Morning climb", "Summit photos", "Descend & return"], meals: "Breakfast" } ],
    thingsToCarry: ["Gloves for grip", "Good shoes", "Water"],
    faq: [ { q: "Is it safe in heavy rain?", a: "We avoid peak downpours; helmets/gloves advised." } ],
    similar: ["Ratangad", "AMK", "Kothaligad"]
  },
  {
    slug: "devkund",
    name: "Devkund Waterfall Trek",
    tagline: "Azure plunge pool in dense forest",
    location: "Bhira • Raigad",
    distanceFromPuneKm: 110,
    difficulty: "Moderate",
    duration: "1D",
    heightM: 720,
    altitudeFt: 2360,
    bestSeason: "Post-monsoon (subject to forest rules)",
    pricePerPerson: 1299,
    includes: ["Travelling", "Instructor", "First Aid"],
    exclusions: ["Meals", "Permits if any"],
    pickupPoints: ["FC Road", "Shivajinagar"],
    joinOptions: [ { from: "Pune", price: 1299, duration: "1D" } ],
    images: [
      "https://images.unsplash.com/photo-1502082553048-f009c37129b9?q=80&w=1600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?q=80&w=1600&auto=format&fit=crop"
    ],
    upcomingDates: ["31 Aug 2025", "07 Sep 2025", "14 Sep 2025"],
    description: "Forest walk to a turquoise waterfall bowl.",
    longAbout: "Forest permissions apply; safety briefings mandatory near the pool.",
    itinerary: [ { day: "Day 1", title: "Waterfall Day", steps: ["Early start", "Forest walk", "Waterfall time (as allowed)", "Return"], meals: "Own / stalls" } ],
    thingsToCarry: ["Rainwear", "Waterproof bag", "Snacks"],
    faq: [ { q: "Is swimming allowed?", a: "Subject to authority & guide decision on flow." } ],
    similar: ["Andharban", "Tamhini", "Kondeshwar"]
  },
  {
    slug: "sandhan-valley",
    name: "Sandhan Valley (Canyon) Trek",
    tagline: "Narrow canyon • rappelling (optional batches)",
    location: "Samrad • Bhandardara",
    distanceFromPuneKm: 200,
    difficulty: "Moderate-Hard",
    duration: "1N/2D",
    heightM: 900,
    altitudeFt: 2950,
    bestSeason: "Post-monsoon & Winter",
    pricePerPerson: 1999,
    includes: ["Travelling", "Instructor", "First Aid", "Technical gear (when applicable)"],
    exclusions: ["Meals unless added", "Personal expenses"],
    pickupPoints: ["FC Road", "Shivajinagar"],
    joinOptions: [ { from: "Pune", price: 1999, duration: "1N/2D" } ],
    images: [
      "https://images.unsplash.com/photo-1501785888041-af3ef285b470?q=80&w=1600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?q=80&w=1600&auto=format&fit=crop"
    ],
    upcomingDates: ["14 Sep 2025", "21 Sep 2025", "28 Sep 2025"],
    description: "Slot-canyon style adventure with boulders; rappelling batches optional.",
    longAbout: "Expect scrambling, narrow passages and starry nights at camp.",
    itinerary: [
      { day: "Day 1", title: "Into the Canyon", steps: ["Depart Pune", "Reach Samrad", "Start descend", "Camp under the stars"], meals: "Own / add-on" },
      { day: "Day 2", title: "Exit & Return", steps: ["Sunrise", "Boulder sections", "Exit valley", "Return to Pune"], meals: "Breakfast" }
    ],
    thingsToCarry: ["Headlamp", "Gloves", "Good shoes", "Extra water"],
    faq: [ { q: "Is rappelling mandatory?", a: "No, only in specific technical batches." } ],
    similar: ["AMK", "Ratangad", "Harishchandragad"]
  },
  {
    slug: "rajgad",
    name: "Rajgad Fort Trek",
    tagline: "The King of Forts • sprawling plateaus",
    location: "Bhor • Pune",
    distanceFromPuneKm: 60,
    difficulty: "Moderate",
    duration: "1D",
    heightM: 1376,
    altitudeFt: 4514,
    bestSeason: "Monsoon & Winter",
    pricePerPerson: 1299,
    includes: ["Travelling", "Instructor", "First Aid"],
    exclusions: ["Meals"],
    pickupPoints: ["Pune pickups"],
    joinOptions: [ { from: "Pune", price: 1299, duration: "1D" } ],
    images: [
      "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=1600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1477414348463-c0eb7f1359b6?q=80&w=1600&auto=format&fit=crop"
    ],
    upcomingDates: ["24 Aug 2025", "31 Aug 2025", "07 Sep 2025"],
    description: "Expansive balekilla and rolling meadows; a rewarding day out.",
    longAbout: "Classic Maratha fort with multiple trail options and big-sky views.",
    itinerary: [ { day: "Day 1", title: "Explore Rajgad", steps: ["Early start", "Payan machi", "Balekilla (time permitting)", "Return"], meals: "Own" } ],
    thingsToCarry: ["Water 2L", "Rainwear", "Snacks"],
    faq: [ { q: "Camping allowed?", a: "Subject to forest/fort rules and batch type." } ],
    similar: ["Torna", "Sinhagad", "Raireshwar"]
  }
];
